.TH STEPS 1OCTTOOLS "28 July 1991"
.SH NAME
xgSteps \- Simple filter bwteen spice output and xgraph.
.SH DESCRIPTION


Usage:

xgSteps <filename> <sig name> ...

Filename is produced by spice with the .print card in a spice deck.

For example, if your spice deck has the line

.print tran in out

and if you save the spice output in file FOO
you can issue the following command:

xgSteps FOO in out

.SH "SEE ALSO"
xgraph, steps(1OCTTOOLS)

