#! /bin/csh -f

set arch = "unknown architecture"
# determine the architecture
if (-e /bin/arch) then
    set arch = `/bin/arch`
else if (-e /bin/machine) then
    set arch = `/bin/machine`
else
    set arch = ""
    if (-e /dynix) then
	set arch = "sequent"
    else if (-e /etc/xlc.cfg) then
	set arch = "rs6000"
    else if (-e /usr/include/apollo) then
	set arch = "apollo"
    endif
endif

echo $arch
