.TH OCT2HILO 1OCTTOOLS "21 May 1990"
.SH NAME
oct2hilo \- Oct to HILO Translator
.SH SYNTAX
.B oct2hilo 
[options] cellname:viewname [options]
.br
.SH DESCRIPTION
.I Oct2hilo
is a translator which reads an Oct cell and generates
a HILO GHDL description.  Currently the Oct cell 
must conform to the Oct Symbolic Policy Specification
and use the MSU 2.2 standard cell library.  Other
libraries are possibe using new .tech files.  The 
next version of Oct2hilo will also create HILO 
descriptions of schematic cells and cells created
by gem.
.PP
The command line options are:
.TP
.B -d
Print detailed debugging information.
.TP
.B -l {tech_file_name,tech_lib}
If file specifies the tech file to use.  If directory
specifies directory to search for appropriate tech file.
The default directory is '~octtools/lib/oct2hilo'.
.TP
.B -t {unit,typ,max}
Specify timing unit, typical, or max timing.  Default is typ.
.TP
.B -o  out_file
Specify name of the HILO description file.  The default is cellname.cct.
.TP
.B -u
Show usage information
.SH HILO
Before compiling the circuit description in HILO be sure to add the
msu library to the library search list.  Use the LIBADD command. 
As HILO does not understand '~' be sure to specify the entire path.
As an example:
.TP
LIB = /cad/octtools/lib/oct2hilo/msu_2.2
.PP
.SH FEATURES
Oct uses a variety of characters in instantiation names and terminal names.
Unfortunately HILO does not tolerate these.  The only character HILO will
accept is '_'.  In addition Oct2hilo prefixes each instantiation with a 'G'
and each terminal with a 'T'.  Oct2hilo makes the following translations:
.PP
.RE
For gates:
.TS
center;
c s s
c n n
.
OCT HILO
norf201_1\tGnorf201_1
norf201.1\tGnorf201__1
norf201_1.13\tGnorf201_1__13
[101]\tG101
.TE
.PP
For terminals:
.TS
center;
c s s
c n n
.
OCT HILO
foo\tTfoo
foo<0>\tTfoo[0]
foo<0>.1\tTfoo_0_1
[345]\tT345
[345].1\tT345_1
.TE

.RE
.SH SEE ALSO
bdnet(1OCTTOOLS)
.SH AUTHOR
John Sutter, M2C
.SH BUGS
Aplenty.  Please report them to jds@m2c.org
.PP
