.TH STEPS 1OCTTOOLS "28 July 1991"
.SH NAME
steps (version 2.0) \- OCT schematic or symbolic to SPICE
.SH DESCRIPTION

Steps can be used to generate a SPICE file starting from a 
symbolic or a schematic facet.

You should use the RPC version of steps (rpc-steps) to annotate the facet.

The command in rpc-steps allow you to add DIRECTION and TERMTYPE 
properties to formal terminals. 
All input formal terminals are regarded as possible  voltage sources. 
Supply terminals are regarded as DC voltage source.

The steps-options command allows you to specify the name of the
SPICE file, the name of another file to be included in the SPICE deck,
the thresholds for minimum parasitics to be included in the SPICE deck
(for symbolic layout)

The basic-connectivity command allows you to specify the name to be
used for the ground node, and the default names for P and N substrate,
in cases in which they cannot be derived otherwise.

Shop around the RPC menu to see what else is available. Most commands
should be self explanatory. 
spice-analyses, for example, lets you decide which analyses you want
SPICE to perform, while spice-output allows you to control the output
you will get from SPICE.

Since parasitics extraction is currently a computing intensive
operation, it is recommended that you use the steps and not rpc-steps
to obtain the SPICE deck.

.SH USAGE
usage: steps [-C real] [-f filename] [-o outfile] [-v] cell:view

   -C:         Threshold cap for parasitics
   -f:         Include user file name
   -o:         Output file name
   -v:         Verbose mode
   cell:view:  Input facet

.SH EXAMPLES

steps nand:symbolic

steps -C 200f -o nand.spice nand:symbolic

.SH AUTHOR
The original STEPS  is by Denis Yip. 
The code has been cleaned up a compressed by Andrea Casotto.

