#!/bin/csh -f

rm -rf library
mkdir tmpdir
cd tmpdir

@ count = 0
foreach i ( $* )
    if ( ! -e $i )  then
	echo "$i does not exist: skipping it and continuing."
	continue
    endif 
    echo copying "($count)" $i ...
    ar x $i
    \rm -f dflttap.o	 	## This is to fix a conflict tap/options
    \rm -f *.SYMDEF *ELEL*
    foreach obj ( * )
	mv $obj $count$obj
    end
    ar q ../library *
    rm -f *
    @ count++
end	

cd ..
rmdir tmpdir
