.TH STEPS 1OCTTOOLS "28 July 1991"
.SH NAME
rpc-steps (version 2.1) \- OCT schematic or symbolic to SPICE
.SH DESCRIPTION

Steps and rpc-steps generate a SPICE file starting from a 
symbolic or a schematic facet.

You should use the RPC version of steps (rpc-steps) to annotate the
facet. Then you should save the facet and run steps to produce the
SPICE deck. You can produce the deck also from the RPC application,
but things will run slower and some parasitics will be ignored.

.SH "SYMBOLIC LAYOUT"

Start rpc-steps by choosing the "steps" entry in the Application menu.
Add DIRECTION and TERMTYPE properties to all formal terminals in the
layout. This can be done easily with the commands in the RPC menu (the
same commands are also available with rpc-symhelp).

Edit each mosfet in the layout. Each input terminal is regarded as a
generic voltage source. The SUPPLY terminals are regarded as DC
voltage sources and all GROUND terminals translate to the node "0"
(zero) in the SPICE deck. 

You can use the build-in models for the devices. If you have different
models you can enter them by inserting a file in the SPICE deck. Do
this using the steps-options command, and you will find a place to
specify a comma separated list of files to be included in the deck.

You can also edit models in Steps with the edit-models command (which
takes an optional string argument, that is the model you want to edit).


The command in rpc-steps allow you to add DIRECTION and TERMTYPE 
properties to formal terminals. 
All input formal terminals are regarded as possible  voltage sources. 
Supply terminals are regarded as DC voltage source.

The steps-options command allows you to specify the name of the
SPICE file, the name of another file to be included in the SPICE deck,
the thresholds for minimum parasitics to be included in the SPICE deck
(for symbolic layout)

The basic-connectivity command allows you to specify the name to be
used for the ground node, and the default names for P and N substrate,
in cases in which they cannot be derived otherwise.

Shop around the RPC menu to see what else is available. Most commands
should be self explanatory. 
choose-analyses, for example, lets you decide which analyses you want
SPICE to perform, while print-and-plot allows you to control the output
you will get from SPICE.

Since parasitics extraction is currently a computing intensive
operation, it is recommended that you use the steps and not rpc-steps
to obtain the SPICE deck.

.SH "SEE ALSO"
steps(1OCTTOOLS)
.br
.SH AUTHOR
Originally Denis Yip
Code has been cleaned up a compressed by Andrea Casotto.

